version: "3"
services:
  www:
    container_name: palomitas-dl-www
    build: www
    labels:
      - traefik.frontend.rule=Host:palomitas-dl.fuken.xyz
      - traefik.port=80
    networks:
      - web
    volumes:
      - ./www:/usr/src/app
      - ./storage/torrents:/usr/share/nginx/html/storage
    links:
      - api
  api:
    labels:
      - traefik.enable=false
    container_name: palomitas-dl-api
    build: server
    restart: always
    ports:
      - 9000:9000
      - 6881:6881
      - 6881:6881/udp
    environment:
      - NODE_ENV=production
      - STORAGE_PATH=/home/node/storage
    volumes:
      # - ./server:/home/node/app
      - ./storage:/home/node/storage
      - ./storage/torrents:/tmp/torrent-stream

networks:
  web:
    external: true
